export const LOGIN_OK = "LOGIN_OK";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const BOOKMARK_DONE = "BOOKMARK_DONE";
export const BOOKMARK_ID = "BOOKMARK_ID";
export const FEED_FETCHED = "FEED_FETCHED";
export const FEED_FETCH_FAILED = "FEED_FETCH_FAILED";